(define (problem menu-week-problem)
  (:domain menu-week)
  (:objects
    monday tuesday wednesday thursday friday - day
    crema_calabaza crema_espinacas gazpacho macarrones ensalada_mixta sopa_marisco arroz_cubana menestra_verduras sopa_fideos espaguetis lentejas paella ensalada_vegana ensalada_pasta ensalada_garbanzos - first
    pechuga_pavo bacalao tortilla_patata dorada_horno albondigas huevos_rellenos tempeh_teriyaki hamburguesa pollo_asado merluza salmon gambas_plancha seitan_guisado filete_ternera costillas_cerdo - second
  )
  (:init
    (= (calories crema_calabaza) 400)
    (= (price crema_calabaza) 3.8)
    (= (calories crema_espinacas) 390)
    (= (price crema_espinacas) 3.9)
    (= (calories gazpacho) 370)
    (= (price gazpacho) 3.5)
    (= (calories macarrones) 700)
    (= (price macarrones) 4.3)
    (= (calories ensalada_mixta) 430)
    (= (price ensalada_mixta) 4.0)
    (= (calories sopa_marisco) 500)
    (= (price sopa_marisco) 5.5)
    (= (calories arroz_cubana) 660)
    (= (price arroz_cubana) 5.0)
    (= (calories menestra_verduras) 400)
    (= (price menestra_verduras) 4.0)
    (= (calories sopa_fideos) 450)
    (= (price sopa_fideos) 3.7)
    (= (calories espaguetis) 710)
    (= (price espaguetis) 4.5)
    (= (calories lentejas) 570)
    (= (price lentejas) 4.2)
    (= (calories paella) 850)
    (= (price paella) 6.5)
    (= (calories ensalada_vegana) 420)
    (= (price ensalada_vegana) 4.3)
    (= (calories ensalada_pasta) 600)
    (= (price ensalada_pasta) 4.6)
    (= (calories ensalada_garbanzos) 500)
    (= (price ensalada_garbanzos) 4.1)
    (= (calories pechuga_pavo) 400)
    (= (price pechuga_pavo) 6.0)
    (= (calories bacalao) 460)
    (= (price bacalao) 6.8)
    (= (calories tortilla_patata) 600)
    (= (price tortilla_patata) 5.2)
    (= (calories dorada_horno) 450)
    (= (price dorada_horno) 7.8)
    (= (calories albondigas) 690)
    (= (price albondigas) 6.0)
    (= (calories huevos_rellenos) 666)
    (= (price huevos_rellenos) 5.0)
    (= (calories tempeh_teriyaki) 480)
    (= (price tempeh_teriyaki) 5.9)
    (= (calories hamburguesa) 900)
    (= (price hamburguesa) 7.2)
    (= (calories pollo_asado) 760)
    (= (price pollo_asado) 6.2)
    (= (calories merluza) 470)
    (= (price merluza) 7.0)
    (= (calories salmon) 530)
    (= (price salmon) 8.0)
    (= (calories gambas_plancha) 420)
    (= (price gambas_plancha) 8.5)
    (= (calories seitan_guisado) 460)
    (= (price seitan_guisado) 5.7)
    (= (calories filete_ternera) 570)
    (= (price filete_ternera) 7.5)
    (= (calories costillas_cerdo) 740)
    (= (price costillas_cerdo) 6.5)
    (incompatible crema_calabaza seitan_guisado)
    (incompatible crema_calabaza dorada_horno)
    (incompatible paella pollo_asado)
    (incompatible arroz_cubana bacalao)
    (incompatible lentejas pollo_asado)
    (incompatible sopa_fideos merluza)
    (incompatible macarrones bacalao)
    (incompatible ensalada_mixta dorada_horno)
    (incompatible macarrones tortilla_patata)
    (incompatible espaguetis tempeh_teriyaki)
    (previous-day tuesday monday)
    (previous-day wednesday tuesday)
    (previous-day thursday wednesday)
    (previous-day friday thursday)
    (= (total-price) 0)
    (same-type crema_calabaza crema_espinacas)
    (same-type gazpacho sopa_fideos)
    (same-type macarrones espaguetis)
    (same-type macarrones ensalada_pasta)
    (same-type arroz_cubana paella)
    (same-type espaguetis ensalada_pasta)
    (same-type lentejas ensalada_garbanzos)
    (same-type pechuga_pavo pollo_asado)
    (same-type bacalao dorada_horno)
    (same-type bacalao merluza)
    (same-type bacalao salmon)
    (same-type tortilla_patata huevos_rellenos)
    (same-type dorada_horno merluza)
    (same-type dorada_horno salmon)
    (same-type tempeh_teriyaki seitan_guisado)
    (same-type hamburguesa filete_ternera)
    (same-type merluza salmon)
  )
  (:goal (and
    (forall (?d - day) (and (assigned-first-day ?d) (assigned-second-day ?d)))
    (assigned-first menestra_verduras monday)
    (assigned-first sopa_marisco wednesday)
    )
  )
  (:metric minimize (total-price))
)